workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      java: 17
      node: 20
      vars:
        PACKAGE_NAME: "com.iftechstudio.html_live_editor"
    
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Copy web assets to Android
        script: |
          mkdir -p android/app/src/main/assets/www
          cp -r dist/* android/app/src/main/assets/www/
      
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      
      - name: Download Gradle wrapper jar
        script: |
          cd android
          mkdir -p gradle/wrapper
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.5.0/gradle/wrapper/gradle-wrapper.jar
          chmod +x gradlew
      
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
      
      - name: Build Android Release AAB
        script: |
          cd android
          ./gradlew bundleRelease
        ignore_failure: true
    
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - giftofhope10.tech@gmail.com
        notify:
          success: true
          failure: true
